version: "3.7"

services:
  app_firstservice:
    build:
      args:
        - SYMFONY_ENV=staging
      context: .
      dockerfile: ./docker/Dockerfile
    networks:
      - symfony

networks:
  symfony:
  traefik:
    external: true

volumes:
  persistent:
